# vim: set syntax=dockerfile :
FROM python:3.10-alpine3.15

COPY requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

COPY app /src/app

CMD ["gunicorn", "-w", "2", "--bind", "0.0.0.0", "--capture-output", "app:create_app()"]

HEALTHCHECK CMD wget localhost:8080/
