---
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src/
    working_dir: /src/
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      FLASK_APP: app/__main__.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    command:
      - flask
      - run
      - --host=0.0.0.0
      - --port=8080
    restart: always
